name: default

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    if: github.ref == 'refs/heads/main'
    name: Run Django Tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: 'refs/heads/main'
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        working-directory: ./django-caretaker
        run: python3 -m pytest
        env:
          SYSTEM_ENV: GITHUB_WORKFLOW
      - name: Create coverage file
        working-directory: ./django-caretaker
        run: python3 -m coverage xml
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: ./django-caretaker/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      - name: Copy Coverage To Predictable Location
        run: cp code-coverage-results.md ./django-caretaker/
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Commit code coverage file
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'code-coverage-results.md'
          author_name: Code Coverage Bot
          author_email: martin@eve.gd
          committer_name: Code Coverage Bot
          committer_email: martin@eve.gd
          cwd: './'
          default_author: github_actor
          message: 'Updating code coverage stats'
          pathspec_error_handling: ignore
          push: true
