name: default

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    if: github.ref == 'refs/heads/main'
    name: Run Django Tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:12.3-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: 'refs/heads/main'
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Show dir
        run: ls
      - name: Pwd
        run: pwd
      - name: Run tests
        run: python manage.py test
        env:
          SYSTEM_ENV: GITHUB_WORKFLOW
